### ISSUE TITLE
Scrollable positioned list

### ISSUE THREAD

**Issue by wisecoders** [Dimibe/grouped_list#10]
hey,

Thanks for the amazing plugin. Could you please check and see if you can include Scorllable positioned list

https://github.com/google/flutter.widgets/tree/master/example/scrollable_positioned_list

**Comment by Dimibe** [comment]
I'll have a look into it but I don't think I will add this in the near future.

**Comment by Dimibe** [comment]
@wisecoders I've just released a package which depends on scrollable_positioned_list. 
Please check it out: https://github.com/Dimibe/sticky_grouped_list
