### ISSUE TITLE
Possible enhancement to indexedItemBuilder ?

### ISSUE THREAD

**Issue by RamithRD** [Dimibe/grouped_list#104]
I have a requirement to show numbering for items in each group, I'd like to know what's the best way to achieve this.

Ex :

```
Group A
  1.
  2.
  3.
Group B
  1.
  2.
Group C
  1.
```
The numbering should reset for each group, therefore the index from `indexedItemBuilder` cannot be used.

Appreciate your input.

**Comment by Fintasys** [comment]
@RamithRD Not sure if it works - I just tested it shortly, but couldn't you have a separate index variable and reset it inside `groupSeparatorBuilder`-method?

**Comment by Dimibe** [comment]
@Fintasys solution should work

**Comment by mikemoore13** [comment]
did not suceed to make this work, could you provide a sample ?
