### ISSUE TITLE
Order Descending Grouped Dates

### ISSUE THREAD

**Issue by saguado69** [Dimibe/grouped_list#106]
Hi,

My code was runnning ok with previous versión of 4.0.0. After upgrading I lost scending ordenring of the groups. Items still ordenring descending but not the groups. If I only order by MMM yyyy is ok but if I order by dd MMMM yyyy then the groups order does not work. I have tryied differents combination with comparator but not succeed.

```
GroupedListView(
                      key: const Key('changeLogGroupedList'),
                      elements: logItems,
                      floatingHeader: true,
                      addAutomaticKeepAlives: true,
                      useStickyGroupSeparators: true,
                      groupBy: (dynamic logItem) => DateFormat('dd MMMM yyyy')
                          .format(logItem.createdAt.toDate()),
                      groupComparator: (value1, value2) =>
                          value2.compareTo(value1),
                      itemComparator: (item1, item2) =>
                          item1.createdAt.compareTo(item2.createdAt),
                      order: GroupedListOrder.DESC,
                      groupSeparatorBuilder: (dynamic logItem) => SizedBox(
```

**Comment by DineshKachhot** [comment]
I have the same kind of issue using grouped_list, I am not able to order groups by date.

**Comment by DineshKachhot** [comment]
**My issue is fixed:** if you are displaying an ordered list, you can disable sorting of `GroupedListView` like `sort: false`.
I am not sure it will help any one, but sharing here as it worked for me.

**Comment by nifhanif** [comment]
> 

Thank you... it work

**Comment by Dimibe** [comment]
Seems to be solved

**Comment by waqadArshad** [comment]
> **My issue is fixed:** if you are displaying an ordered list, you can disable sorting of `GroupedListView` like `sort: false`. I am not sure it will help any one, but sharing here as it worked for me.

Thanks a lot @DineshKachhot

**Comment by lakoliu** [comment]
Thank you, @DineshKachhot, that was just what I needed!
