### ISSUE TITLE
List not scrolling to the end

### ISSUE THREAD

**Issue by BFamzz** [Dimibe/grouped_list#114]
I am using the following code snippet to auto scroll to the end of a list:

```
SchedulerBinding.instance!.addPostFrameCallback((_) {
      scrollController.animateTo(
      scrollController.position.maxScrollExtent, 
      duration: const Duration(milliseconds: 3), 
      curve: Curves.easeOut
    );
});
return GroupedListView<Chat, DateTime>(
    controller: scrollController,
.
.
.
```

However, one or two items are not showing until a manual scroll is initiated.

How can I implement auto scrolling to the end of the list?

P.S. the scrolling implementation above works for ListView

Thanks.

**Comment by glintpursuit** [comment]
@BFamzz did found the solution ?

**Comment by BFamzz** [comment]
@glintpursuit I found the answer at the end of the documentation on the ReadME. See the screenshot.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/38426051/180937292-feb6423c-0b4c-439b-bfed-70d8bcfe4284.png">
