### ISSUE TITLE
Jump to a specific Group Header 

### ISSUE THREAD

**Issue by MohammedElotol** [Dimibe/grouped_list#116]
Can I programmatically Scroll to a specific header or to an item?
I need to know the index of the header in the list

**Comment by mohammedebrahim1** [comment]
got a solution ?

**Comment by pradeep14598** [comment]
did you guys got any Solution?

**Comment by mohammedebrahim1** [comment]
@pradeep14598  my solution was make a method that's grouped items separately and use list view to scroll to header with it's index

**Comment by pradeep14598** [comment]
@MohammedElotol i have done by sorting a whole list with group header name  and  find a first index of each group header and then passed that index to scroll to that group header

**Comment by Dimibe** [comment]
Hello, 
maybe the [sticky_grouped_list package](https://github.com/Dimibe/sticky_grouped_list) which I also published helps you for that problem. It is based on the scrollable_positioned_list which can be programmatically scrolled. My package adds the group functionality to it.  

I won't add any solution to this package here.
