### ISSUE TITLE
Scrollbar indicator not reaching the end of a list.

### ISSUE THREAD

**Issue by icnahom** [Dimibe/grouped_list#12]
Hello Dimibe, 

This is a great package! 

One Issue I have found when setting `useStickyGroupSeparators` to `true` is that the scrollbar indicator does not reach to the end of the list.

**Comment by Dimibe** [comment]
I'll look into it

**Comment by Dimibe** [comment]
@icnahom Could you please provide an example which shows the problem?

**Comment by icnahom** [comment]
It's easy to reproduce the bug. Here's what you do: Wrap the GroupedListView widget with a Scrollbar widget. Now scroll and see the scroll bar while scrolling to the end of the list. 
I hope you will catch the problem.

**Comment by Dimibe** [comment]
@icnahom Issue is fixed in version 3.0.0
