### ISSUE TITLE
add support for nested grouping

### ISSUE THREAD

**Issue by tomasweigenast** [Dimibe/grouped_list#120]
Add support for nested grouping. For example, If a product is added to a category, which is parent of another category, for example:

Category: `Soda` is inside category `Drinks`

It would be very useful to add the ability to group by `Drinks`, and then by `Soda`

**Comment by Dimibe** [comment]
Hey @tomasweigenast, in my opinion this feature brings to much complexity to the package, so I won't add it. If you have a good and easy to use solution to this problem, I would appreciate a PR from you.
