### ISSUE TITLE
White background on sticky header.

### ISSUE THREAD

**Issue by icnahom** [Dimibe/grouped_list#13]
This fix is crucial for the use of sticky date headers which is used vastly by different applications.

Here's what's happening. 
![iPhone X-XS-11 Pro – 1@2x](https://user-images.githubusercontent.com/60504285/77256529-009b1a80-6c80-11ea-8eb1-9ba5b8bf1bba.jpg)

**Comment by Dimibe** [comment]
I will think about it how to change this. Thanks for the detailed visulization.

**Comment by Dimibe** [comment]
@icnahom Version 3.0.0 was just release. Sticky Headers are now default and a new option `floatingHeader` is available. When set to `true` the sticky headers should behave like you described. Let me know if any problem occurs.

**Comment by icnahom** [comment]
I can't center the header like the Image I posted up there. Can you show me an example of how to do this? Because when I use the widget Center it pushed it to the middle and when I remove Center the overlapped header inside the list gets messed up.

**Comment by Dimibe** [comment]
@icnahom Try this: 
```dart
groupSeparatorBuilder: (value) => Padding(
      padding: const EdgeInsets.all(8.0),
      child: Container(
        decoration:
            BoxDecoration(color: Colors.blue, borderRadius: BorderRadius.all(Radius.circular(20))),
        width: 100,
        height: 30,
        child: Center(
          child: Text(
            value,
            style: TextStyle(
                fontSize: 18.0, color: Colors.red, fontWeight: FontWeight.bold),
          ),
        ),
      ),
    ),
```
