### ISSUE TITLE
Please add reverse support for SliverGroupedListView

### ISSUE THREAD

**Issue by expertdev-designer** [Dimibe/grouped_list#141]

**Comment by berdibekovaG** [comment]
It would be great if it were possible to add smth like "scrolltoindex" or supporting gropedListView with scrollListener

**Comment by santhoshmittapally** [comment]
It would be great if it were possible to add smth like "scrolltoindex" or supporting gropedListView with scrollListener

**Comment by Dimibe** [comment]
Can be done with `order` and `groupComparator` and  `itemComparator`
