### ISSUE TITLE
Suggestion: ItemCount for adding extra widget

### ISSUE THREAD

**Issue by Devlonoah** [Dimibe/grouped_list#144]
Hi,
I'm suggesting that itemCount be added to the parameters available.

As this will allow adding an extra widget :
In a scenario where i plan to add a  Text or a button [View All] to te end of the item list,
Of course the only way to achieve this will be to add 1 to the length of the data being use.
a pseudocode to explain what i meant:
`var listOfFruit = ["Orange","Apple","Pawpaw"];

ListView.builder(
itemcount: listOfFruit.length +1,
itemBuilder:(context,index){
if(index ==0){
show Add more Button
}
else{
show all fruit
}
}`

**Comment by Dimibe** [comment]
Hi @Devlonoah, 
There are similar requests to this one but I think adding the itemcount option to the package will make usage too complicate. 
Instead I am thinking of an option like `footerWidgets` / `headerWidgets` where you can provide a `List<Widget>` and those items will then be automatically placed on top or below the list. Will this feature meet your needs?

**Comment by xxJeevesxx** [comment]
Do you think this will make it into the next update?

**Comment by ZakwanIbrahim3321** [comment]
you can achieve it like this

<img width="606" alt="Screenshot 2023-10-13 at 6 23 36 PM" src="https://github.com/Dimibe/grouped_list/assets/51742205/c549b306-cfef-4483-a7ef-7c41bb9b5c4b">

**Comment by Dimibe** [comment]
Closing this in favor of #152
