### ISSUE TITLE
Disable divider between list items

### ISSUE THREAD

**Issue by andzejsw** [Dimibe/grouped_list#15]
I have divider line between my list items, which one i want to disable. How can i do that!?

**Comment by Dimibe** [comment]
@andzejsw Thanks. Will be fixed in the next bugfix release today.

**Comment by Dimibe** [comment]
Version 2.0.1 should be available in a few minutes. Let me know if everything works fine now.

**Comment by andzejsw** [comment]
Everything is fine. Big tnx!
