### ISSUE TITLE
grouping by date string seems not to work

### ISSUE THREAD

**Issue by bruoff** [Dimibe/grouped_list#16]
Hi Dimibe, 

thank for your work on this great package! 

I'm trying to group my listitems by a String which contains a date "2020-03-28". Seems that it's not grouping correctly. When I add an item with the String "2020-03-29" and then again a item with "2020-03-28" I get 3 different groups but as far as I understand there should be only 2.

**Comment by Dimibe** [comment]
@bruoff Thanks for letting me know. A new version with this bug fixed will be available later today.

**Comment by Dimibe** [comment]
Version 2.0.1 should be available soon. Let me know if everything works fine know.

**Comment by bruoff** [comment]
Hi Dimibe, 

thanks for the ultra fast response! Everything works now. 

Regards
Ben
