### ISSUE TITLE
Can this implement a chat like list ?

### ISSUE THREAD

**Issue by qq741957916** [Dimibe/grouped_list#170]
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-f3e7ce10-3009-45cf-ba27-8cc425cf32cc/676ee65a-8f99-4c37-918e-803fdfc39c43.MP4](url)
thank you

**Comment by Dimibe** [comment]
See https://github.com/Dimibe/grouped_list/blob/main/example/lib/chat_example.dart
