### ISSUE TITLE
Wrong sticky header on first display of scrolled list

### ISSUE THREAD

**Issue by deakjahn** [Dimibe/grouped_list#181]
**Describe the bug**
When using a grouped list inside a `Scrollbar` and passing it a scroll controller, depending on the scroll position, it might display with some item in the middle rather than the very first item. In this situation the top sticky header isn't correct, it shows the first item's group even if we're somewhere in the middle of the list. Only the first slight movement of the list fixes it.

**Expected behavior**
Correct sticky header upon initial display.

**Information:**
 - Dart version: 2.19.6
 - Flutter version: 3.7.12
 - Platform: Android
 - Package version: 5.1.2

**Comment by deakjahn** [comment]
A quick solution. I don't PR it yet, first, it's too easy, second, I don't know whether you would think it dangerous for anything else. It looks like simply removing the condition would work:

[    if (widget.reverse) {
      _ambiguate(WidgetsBinding.instance)!.addPostFrameCallback((_) {
        _scrollListener();
      });
    }](https://github.com/Dimibe/grouped_list/blob/14143b61c7472e64ff02f4aebbb555497181b8cf/lib/grouped_list.dart#L286-L290)

Just call `_scrollListener()` on the next frame in any case, not just for reverse.

**Comment by Dimibe** [comment]
Fixed with #198
