### ISSUE TITLE
Feature Request: Custom Header Location

### ISSUE THREAD

**Issue by aljibbs** [Dimibe/grouped_list#184]
Is it possible to have the header on a different location. For example I will like to use the title of my app bar as the group header, in other words the title of my appbar should change to reflect the title of my group when the list scolls. The appbar's title should be able to detect the scroll position and change accordingly to reflect the title of the group.

**Describe the solution you'd like**
The use case here is that, I have a horizontal listview and I'll like to position the group header on top of the listview instead of having it as part of the listview.

So I can have it like this.

```
Column(
   children: [
         Text('Group Title'),
         // Horizontal grouped listview
          ListView(),
    ]
)
```

**Comment by Dimibe** [comment]
Hi @aljibbs, 
This will be resolved with #82. But currently there is no timeline when this feature is implemented.
