### ISSUE TITLE
Highlight current group separator

### ISSUE THREAD

**Issue by AndreaRicchi** [Dimibe/grouped_list#193]
It would be nice to have the possibility to highlight the current separator:

![image](https://github.com/Dimibe/grouped_list/assets/17642033/51117de7-ef27-4caa-9e79-f1c5f6fae492)

In this case the default "C" is transparent and the current group separator "A" has a different background.

Currently, I'm using a `GroupedListView<dynamic, String>`

**Comment by Dimibe** [comment]
Hi @AndreaRicchi, 
this feature is included in #126. With that you can define a `groupStickyHeaderBuilder ` which is used for the sticky header. 
It will be available in the next release, which will be available in the next week.

**Comment by AndreaRicchi** [comment]
> Hi @AndreaRicchi, this feature is included in #126. With that you can define a `groupStickyHeaderBuilder ` which is used for the sticky header. It will be available in the next release, which will be available in the next week.

When will the next release be available?
