### ISSUE TITLE
Sticky Headers

### ISSUE THREAD

**Issue by Dimibe** [Dimibe/grouped_list#2]
Provide an option for sticky group separators.

**Comment by bhenav** [comment]
Hello @Dimibe , 

when do you intend to do that?

**Comment by sameterap** [comment]
Hi @Dimibe ,

I guess this sticky headers are really needed in this plugin. We are waiting for that. Thanks

**Comment by Dimibe** [comment]
@sameterap @bhenav when all goes as planned the feature will be available within the next week.

**Comment by sameterap** [comment]
> @sameterap @bhenav when all goes as planned the feature will be available within the next week.

Thank you. It's appreciated.

**Comment by Dimibe** [comment]
@sameterap Feature available in release 2.0.0. 
Due to some major refactorings a new major version was released.
For usage just set the new property `useStickyGroupSeparators` to `true`.

**Comment by triple-j-95** [comment]
Hi @Dimibe 
Are you planning to add useStickyGroupSeparators to SliverGroupedListView?
(Or is there another way to stick the grouping header with SliverGroupedListView?)
Thanks!
