### ISSUE TITLE
RefreshIndicator implementation

### ISSUE THREAD

**Issue by CripyIce** [Dimibe/grouped_list#20]
I've implemented `GroupedListView` inside a `RefreshIndicator` and it seems to work only when list is long enough and scrollable.
For example, when the list contains only one value `RefreshIndicator` cannot be performed.
Any ideas?

**Comment by Dimibe** [comment]
if you set `physics: const AlwaysScrollableScrollPhysics()` on the `GroupedListView` it should work.
