### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by leonardo2204** [Dimibe/grouped_list#28]
Hello! Quick question, do you have any plans of adding a footer on the list?
I think it should be simple to implement yet pretty useful. If you agree I can open a PR.

Thanks!

**Comment by nitish9065** [comment]
Hey..please help me how do i add footer to each individual section??

**Comment by HelgeSverre** [comment]
This would be a nice feature, it would make it possible to easily add a "This months total" to each group in interfaces like this:

<img width="464" alt="image" src="https://github.com/Dimibe/grouped_list/assets/1089652/9356c828-a703-4079-95e2-560c3a45177f">

**Comment by 4-alok** [comment]
#189 take a look at this

**Comment by Dimibe** [comment]
Done with #189. Will be available in version 6.0.0 which will be released in the next days.
