### ISSUE TITLE
Sort items within group

### ISSUE THREAD

**Issue by tcoursen3** [Dimibe/grouped_list#30]
Is there a way to sort the items with the group?

**Comment by Dimibe** [comment]
Items of Type String or Objects which implement the Comparable Interfaxe are sorted alphabetically/according their comparable implementation.

**Comment by tcoursen3** [comment]
Thank you.  This worked perfectly.  I am new to Dart and flutter.
Your widget is great.  Easy to use, and works and looks great.  Appreciate you making your work public.
