### ISSUE TITLE
groupBy: String

### ISSUE THREAD

**Issue by andzejsw** [Dimibe/grouped_list#31]
I have tested, that "groupBy" attribute works, if i am using integer value. It would be nice, that there would be option to group items by string value.

**Comment by Dimibe** [comment]
Hello @andzejsw, the `groupBy` attribute works already on type string. Check the [example code](https://github.com/Dimibe/grouped_list/blob/22be7aed69d79288b1e62d965fa44a97719f9c1c/example/example.dart#L29) for more information. Let me know if anything does not work as expected. 

Best regards

**Comment by andzejsw** [comment]
> Hello @andzejsw, the `groupBy` attribute works already on type string. Check the [example code](https://github.com/Dimibe/grouped_list/blob/22be7aed69d79288b1e62d965fa44a97719f9c1c/example/example.dart#L29) for more information. Let me know if anything does not work as expected.
> 
> Best regards

Tnx. My bad.
