### ISSUE TITLE
not working with group by type boolean

### ISSUE THREAD

**Issue by yalva** [Dimibe/grouped_list#39]
Its not working if we use the bool as group by field like this
GroupedListView<dynamic, bool>

This is the error
flutter: state: _GroupedLisdtViewState<dynamic, bool>#b8373):
flutter: The method '>' was called on null.
flutter: Receiver: null
flutter: Tried calling: >(0)

**Comment by Dimibe** [comment]
@yalva Fixed in version 3.0.1

**Comment by yalva** [comment]
Brilliant! thank you.
