### ISSUE TITLE
List of Model?

### ISSUE THREAD

**Issue by komputerboy** [Dimibe/grouped_list#4]
Hi,

I want to ask, how to grouping list data if my list is a model, like this:

```
List<MyModel> mylist = {
MyModel("name" : "aaa", "age":"22"),
MyModel("name" : "bbb", "age":"21"),
MyModel("name" : "ccc", "age":"22"),
}
```

thanks

**Comment by komputerboy** [comment]
sorry, i have found it

thank you

**Comment by beatrizsampaiob** [comment]
sorry, I have the same doubt. can you tell me how to solve it?
