### ISSUE TITLE
Ripple effect not working.

### ISSUE THREAD

**Issue by icnahom** [Dimibe/grouped_list#40]
Hello again, 

Using `ListTile` or `InkWell` in the `itemBuilder` does not show the ripple effect when tapping on an item. But functions like `onTap` and `onLongPress` work, it's just the effect that doesn't work.

**Comment by Dimibe** [comment]
Hi @icnahom, I will look into it this weekend.

**Comment by Dimibe** [comment]
Hey @icnahom, 
I tested it and there seems to be no difference between a normal ListView and the GroupedListView. Here is a gif how it looks on my device. 
![ripple](https://user-images.githubusercontent.com/15692917/82749520-05786980-9daa-11ea-9667-4462fee7ec7c.gif)

**Comment by icnahom** [comment]
Okay I will check it on the emulator and try to resolve the problems on my side. I will close this for now. Thanks for giving it a check!
