### ISSUE TITLE
First group separator has wrong theming when using dark mode

### ISSUE THREAD

**Issue by michaelmairegger** [Dimibe/grouped_list#42]
Hi,

i use the brightness: Brightness.dark within ThemeData. Unfortunately the first group header does not use the dark color as background and therefore the header is not visible. If I set the property floatingHeader to true then the background is set correctly

|floatingHeader = false|floatingHeader = true|
|---|---|
|![Anmerkung 2020-05-22 143144](https://user-images.githubusercontent.com/4341039/82667874-fc1bbf80-9c38-11ea-8fde-ffcd8dd58692.gif)|![Anmerkung 2020-05-22 143044](https://user-images.githubusercontent.com/4341039/82667871-fb832900-9c38-11ea-9f7b-f67f929f48bd.gif)|

Remarks: There is no issue with version 2.3.1
Possibly related with #41

**Comment by Dimibe** [comment]
@michaelmairegger It should be fixed in version 3.1.0. When using this version please set all properties like you did before, so there should be no need to use the floatingHeader property anymore.
Let me know if something still does not work as expected. 
Best regards
