### ISSUE TITLE
Use of groupSeparator property

### ISSUE THREAD

**Issue by jadenwjh** [Dimibe/grouped_list#43]
groupSeparatorBuilder: (String value) => Padding(
            padding: EdgeInsets.fromLTRB(15, 40, 10, 10),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(
                  value,
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.w300),
                ),
              ],
            ),
          ),

Above is my groupSeparator for the widget. I have set useStickyGroupSeparators to true. This results in the following:

<img width="433" alt="Screen Shot 2020-05-27 at 23 26 12 PM" src="https://user-images.githubusercontent.com/62279469/83040395-ca0fc080-a071-11ea-8d34-9cc157d050e9.png">

How do i get rid of the space between the appBar and Monday, but preserve the space between Monday's last Card and Saturday etc?

**Comment by Dimibe** [comment]
Hi,

there is currently no separate option to do something like that. All
groupSeparators are build like defined in the builder method.
So the only possible solution is to modify the implementation of your
builder method and do a distinction inside it. E.g. if the provided value
is Monday then set the top padding to 10 in all other cases to 40 like you
are doing currently.
I know that's not best coding practice to hardcode things like that but for
a first tests I would go with that. If all works like expected you maybe
find a better solution to distinguish inside the method.

Hope this will help you.

Best regards
Dimitrios

Ps: Nice to see my package finds usage in your app. Looks great ;)

Am Mi., 27. Mai 2020 um 17:30 Uhr schrieb Jaden <notifications@github.com>:

**Comment by jadenwjh** [comment]
I see, thank you so much for your prompt reply! Yes your package seems to be the neatest and easiest to use hence I have decided to use it for my app, good job!
