### ISSUE TITLE
Implement new sorting options

### ISSUE THREAD

**Issue by jadenwjh** [Dimibe/grouped_list#44]
Hi I am looking to sort the elements by the days in the week instead of just ASC and DESC.
I tried to edit from the original sort for ASC.
These are the edits I have made to the grouped_list.dart file, but the app still remains to retain the original ASC sorting properties. Am I missing a step?

<img width="1757" alt="Screen Shot 2020-05-31 at 23 08 18 PM" src="https://user-images.githubusercontent.com/62279469/83355771-13268400-a394-11ea-8aac-f6d6ae4df60c.png">

**Comment by jadenwjh** [comment]
i realized that i need to use toString() to convert T object to String Object and also change the pubspec.yaml file of my app. Issue solved

**Comment by Dimibe** [comment]
Hi @jadenwjh, 
I've designed the package so that there should be no need to to override the sorting since sorting can be controlled with the comparable interface. 
If you want a custom sorting I would suggest you to do it like I recommend here in the issue https://github.com/Dimibe/grouped_list/issues/32. This was almost exactly the same what you are trying to do. 

The advantage of this solution is that you can reuse the list with other items. Your solution will not work in case you want to use the list somewhere else where the grouping is not by days.

**Comment by jadenwjh** [comment]
this is a very well thought solution, thank you!

**Comment by jadenwjh** [comment]
Hi @Dimibe,
I have tried the solution you suggested. The code runs, but the items are now separated individually, instead of falling under the same category this time.

<img width="438" alt="Screen Shot 2020-06-01 at 01 09 23 AM" src="https://user-images.githubusercontent.com/62279469/83358231-ba131c00-a3a4-11ea-80b5-c16556e0ffee.png">

**Comment by Dimibe** [comment]
@jadenwjh can you send me the Code from your objects/compareTo implementation?

**Comment by jadenwjh** [comment]
class Task implements Comparable {
  final String day;
  final String name;
  final String index;
  final String time;

  Task(this.index, this.name, this.day, this.time);

  @override
  int compareTo(other) {
    return index.compareTo(other.index);
  }
}


List<Task> _elements = [
  Task('1', 'Study', 'Monday', '16:00'),
  Task('1', 'Run', 'Monday', '17:30'),
  Task('1', 'Eat', 'Monday', '20:00'),
  Task('2', 'Study', 'Tuesday', '16:00'),
  Task('2', 'Eat', 'Tuesday', '17:00'),
  Task('3', 'Study', 'Wednesday', '16:00'),
  Task('4', 'Study', 'Thursday', '16:00'),
  Task('4', 'Run', 'Thursday', '20:00'),
  Task('5', 'Study', 'Friday', '16:00'),
  Task('5', 'Study', 'Friday', '20:00'),
  Task('5', 'Play', 'Friday', '22:00'),
  Task('6', 'Study', 'Saturday', '16:00'),
  Task('7', 'Study', 'Sunday', '16:00'),
];

**Comment by Dimibe** [comment]
The code seems correct so far. Only thing I think that can be wrong now is the groupBy function. Did you group by the element itself like I mentioned in the other issue? 
`groupBy: (element) => element`

**Comment by jadenwjh** [comment]
yup I did, here is the portion of the code in question:

body: GroupedListView<dynamic, Task>(
          order: GroupedListOrder.ASC,
          groupBy: (element) => element,
          elements: _elements,
          useStickyGroupSeparators: false,
          groupSeparatorBuilder: (element) => Padding(
            padding: (element.day == 'Monday'
                ? EdgeInsets.fromLTRB(15, 10, 10, 10)
                : EdgeInsets.fromLTRB(15, 40, 10, 10)),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Header(
                  text: element.day,
                  size: 20,
                  italic: false,
                ),
              ],
            ),
          ),

Once again thank you for taking your time to reviewing this problem

**Comment by jadenwjh** [comment]
@Dimibe Might it be because the input in your example is a List of Maps, but here we only have a List of Objects?

**Comment by Dimibe** [comment]
@jadenwjh No this is not a problem. Did you reset the implementation of the _sortElements method inside the grouped list back to how it was?
I tested it with your code and it's working.

**Comment by jadenwjh** [comment]
@Dimibe it did not work for me. I moved the code over to a new flutter app and re-imported the package but the items are still separated as per above.

**Comment by jadenwjh** [comment]
i've decided to go with switch-case to convert the indexes into words, and use the suggestion you provided to sort the time attribute instead. This helped me achieved better results too, thanks.

<img width="458" alt="Screen Shot 2020-06-01 at 06 18 29 AM" src="https://user-images.githubusercontent.com/62279469/83363923-bb0d7300-a3cf-11ea-9b6d-40b4cdbf01cd.png">
