### ISSUE TITLE
It always show 'Team C' on the screen.

### ISSUE THREAD

**Issue by function2000** [Dimibe/grouped_list#46]
It always show 'Team C' on the screen when run your example.  Please check.

**Comment by Dimibe** [comment]
@function2000 Thank you for notifying me, I fixed the example code. 
You can view [my latest commit](https://github.com/Dimibe/grouped_list/commit/4ae7bf1112cf656a4e4f20c2fda1375f976c0256) to see what was not working and you can find a more detailed explanation why this was not working [here](https://github.com/Dimibe/grouped_list/issues/41#issuecomment-633197273).
