### ISSUE TITLE
OnTap event responsive accuracy low

### ISSUE THREAD

**Issue by MihaiRebegea** [Dimibe/grouped_list#53]
I have some issues with the onTap/onPressed events on Items of Grouped list.
I get an 70-80% response accuracy.
When I use a Listview directly the onTap events are triggered accurately as expected - so I can only draw the conclusion that it's related to the grouped list.

I need to make the items of the grouped list selectable - I used InkWell or GestureDetector and I get the same response accuracy of 70-80%.
I also have an IconButton on my ListItem which has the same response accuracy.

I just updated the library from version 3.1.0 to version 3.3.0 but I don't see any improvement.

Thanks,

**Comment by Dimibe** [comment]
Hi @MihaiRebegea, can you provide a more detailed example? 
I've just tested it with a `GestureDetector` and it seems to work fine. 
```dart
        GroupedListView(
          itemBuilder: (_, element) {
            return GestureDetector(
              onTap: () => [..],
              child: [..]
            );
          },
          [...]
       );
```

**Comment by MihaiRebegea** [comment]
Hi @Dimibe I just created a more light weight example that I wanted to share here but I can't reproduce the issue anymore.
I need to investigate further, maybe I use a combination of things which interacts with the GestureDetector
I'll close the issue for now.

Thank you for looking into it.
