### ISSUE TITLE
Can not with List Model

### ISSUE THREAD

**Issue by vohoangtuit** [Dimibe/grouped_list#55]
I have a model Product, add List data with this model, but can not group by with that, run show error: Class 'Product' has no instance method 'call'.
Receiver: Instance of 'Product'
Tried calling: call(Product)

-------------
class Product{
  String id;
  String name;
  String price;
  String image;
  String create_at;

  Product({this.id, this.name, this.price, this.image, this.create_at});
}

**Comment by Dimibe** [comment]
@vohoangtuit Can you please provide the code of the GroupedList widget as well.

**Comment by vohoangtuit** [comment]
Hi, this my code, please support me
https://github.com/vohoangtuit/flutter_custom_listview/blob/master/custom_listview/lib/views/listview_group_by_header.dart

**Comment by zamarrong** [comment]
I have the same issue when trying to set the group by with a property from custom class list object
