### ISSUE TITLE
first item is not in alphabetical order

### ISSUE THREAD

**Issue by Sergio719** [Dimibe/grouped_list#56]
Hi, I have a grouped list that works very well except that the first item in the grouped list is not il alphabetical order as the following ones. Note the original list is already ordered in alphabetical order.
So I cannot explain this behaviour. Maybe a bug?

please see the attached example.

Thanks in advance for your help! and congratulations for the nice tool.
Sergio

![Simulator Screen Shot - iPhone 11 - 2020-08-22 at 22 11 15](https://user-images.githubusercontent.com/70075125/90965008-8982e000-e4c4-11ea-87ea-7f579472bf96.png)

**Comment by Dimibe** [comment]
There is an option `sort` which you can set to 'false' if your list is presorted. 

I was not able to able to reproduce the problem.

**Comment by Dimibe** [comment]
In Version 3.5.0 there is now an option `itemComparator` which can be used for a custom sorting between items in a group. Please try this.
