### ISSUE TITLE
Unable to group Map

### ISSUE THREAD

**Issue by shanthosh2910** [Dimibe/grouped_list#57]
I have a list of map `List<SongInfo> songs;`

![image](https://user-images.githubusercontent.com/22300553/92608056-82d0d700-f2d2-11ea-951e-63655cef5cc7.png)

This is how I will use the normal `ListView`

```
Widget _buildApps(songs) => ListView.builder(
      itemCount: songs.length,
      itemBuilder: (BuildContext context, int index) =>
          _buildRow(songs[index]));

  Widget _buildRow(SongInfo song) {
    final saved = musicModel.getSongs().contains(song.filePath);
    return ListTile( title: Text("${song.title}"));
```
Now I want to group all the songs by `song.album`.

**Comment by Dimibe** [comment]
@shanthosh2910  What have you tried so far and what is not working?

**Comment by shanthosh2910** [comment]
I tried this. Getting `NoSuchMethodError` 
```
Widget _buildApps(songs) => GroupedListView(
      elements: songs,
      groupBy: (song) => song.album,
      itemBuilder: (context, song) => _buildRow(song));
```

**Comment by Dimibe** [comment]
@shanthosh2910 
As mentioned in the readme, you neeed to specify `groupSeparatorBuilder` which is a function which returns a widget for the group header (equal to `itemBuilder` for items). There you can customize the group header as you like. 

In your case a very basic solution would be something like this: 
```
groupSeparatorBuilder: (album) => Text('$album'),
```

**Comment by shanthosh2910** [comment]
Thank you!!!
