### ISSUE TITLE
Solution to lack of @required on required parameters

### ISSUE THREAD

**Issue by xJon** [Dimibe/grouped_list#62]
I found that it is easy to accidentally forget to use the required parameters for `GroupedListView()` that appear in the documentation; while doing so, there will be no compile-time error, and the run-time error one would get is rather cryptic:
```
The method 'call' was called on null.
Receiver: null
Tried calling: call()
```
I understand `@required` wasn't added because of the different builder types, but is there a way to make this more obvious?
Thank you!

**Comment by Dimibe** [comment]
@xJon Fixed with release 3.7.0
