### ISSUE TITLE
Sort freely. Don't asc and don't desc

### ISSUE THREAD

**Issue by mdmota** [Dimibe/grouped_list#65]
How do I leave the natural ordering of the list?
My list is for months / year.

I need it to look like this:
12/2020
....
...
...
01/2021
...
...
02/2021
...
...

**Comment by Dimibe** [comment]
Hi @mdmota, 

can you please provide some example code and the expected and actual output.

For sorting the items itself and values of the groupBy function are compared. 
Normally the list sorts the groups and items according their natural order whereby DESC reverses this order. So without setting the order property or setting ist ASC you should be fine. 

There are also two parameters where you can define your own comparator for the groups and items.
