### ISSUE TITLE
Slivers support

### ISSUE THREAD

**Issue by DenchikBY** [Dimibe/grouped_list#71]
Need a possibility to use grouped list based on SliverList inside CustomScrollView and NestedScrollView.

**Comment by Dimibe** [comment]
Will look into it

**Comment by fenchai23** [comment]
> Need a possibility to use grouped list based on SliverList inside CustomScrollView and NestedScrollView.

does `SliverToBoxAdapter` not fix the issue?

**Comment by DenchikBY** [comment]
> > Need a possibility to use grouped list based on SliverList inside CustomScrollView and NestedScrollView.
> 
> does `SliverToBoxAdapter` not fix the issue?

It works only with `shrinkWrap: true`, but it doesn't fit

**Comment by fenchai23** [comment]
> > > Need a possibility to use grouped list based on SliverList inside CustomScrollView and NestedScrollView.
> > 
> > does `SliverToBoxAdapter` not fix the issue?
> 
> It works only with `shrinkWrap: true`, but it doesn't fit

for me it gets real laggy but everything shows. Like REAL laggy. I haven't tried without sliverToBox Adapter. Will try today.

**Comment by DenchikBY** [comment]
> > > > Need a possibility to use grouped list based on SliverList inside CustomScrollView and NestedScrollView.
> > > 
> > > 
> > > does `SliverToBoxAdapter` not fix the issue?
> > 
> > 
> > It works only with `shrinkWrap: true`, but it doesn't fit
> 
> for me it gets real laggy but everything shows. Like REAL laggy. I haven't tried without sliverToBox Adapter. Will try today.

obviously, as `shrinkWrap` make list render all items at once

**Comment by fenchai23** [comment]
just discovered this O.O I will have to find a way to remove shrinkwrap now 😔

**Comment by cstsortan** [comment]
https://github.com/Dimibe/grouped_list/pull/98 is a fix, but removes support for sticky header and reversed list

**Comment by Dimibe** [comment]
SilverGroupList was added in #112. For an example see `example/lib/example_silver.dart`
