### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 0..14: 16

### ISSUE THREAD

**Issue by easydo247** [Dimibe/grouped_list#77]
```dart
class LongListPage extends StatefulWidget {
  @override
  _LongListPageState createState() => _LongListPageState();
}

class _LongListPageState extends State<LongListPage> {
  List<Map<String, int>> _elements = List<Map<String, int>>.generate(
      30, (int index) => {'name': index, 'isEven': index % 2 == 0 ? 0 : 1});

  List<Map<String, int>> _filterElements = [];

  @override
  void initState() {
    _filterElements = _elements;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          TextButton(
            onPressed: () {
              setState(() {
                _filterElements = _elements.where(
                  (element) {
                    return element['name'] % 2 == 0;
                  },
                ).toList();
              });
            },
            child: Text('only even'),
          ),
          Expanded(
            child: GroupedListView<Map<String, int>, int>(
              elements: _filterElements,
              groupBy: (element) => element['isEven'],
              separator: Divider(),
              groupComparator: (value1, value2) {
                return value1.compareTo(value2);
              },
              useStickyGroupSeparators: true,
              groupSeparatorBuilder: (value) {
                return Text(
                  value.toString(),
                  style: TextStyle(
                    backgroundColor: Colors.red,
                  ),
                );
              },
              itemBuilder: (context, element) {
                return Text(element['name'].toString());
              },
            ),
          ),
        ],
      ),
    );
  }
}
```
When I scroll to the bottom of the list and then I try to filter the list content by pressing the "only even" button I get:

RangeError (index): Invalid value: Not in inclusive range 0..14: 16
The relevant error-causing widget was
GroupedListView<Map<String, int>, int>

**Comment by Dimibe** [comment]
Will look into it

**Comment by romain-bajoit-iot-d** [comment]
This only seems to happen when the elements are changed and the new GroupedListView does fit completely on the screen, the scrollListener is not trigger then and thus _showFixedGroupHeader receive the same previous topElementIndex which might trigger a RangeError if you had scroll down enough in a previously created GroupedListView.

**Comment by ericel** [comment]
With the main flutter ListView, this is usually because of a missing itemCount. I am quite sure how this library deals with that here.
Try something like `semanticChildCount` to set the initial itemCount. That should fix the problem.

**Comment by grammatnMcK** [comment]
Hey that's a bug and I have it as well. @Dimibe any news there regarding this issue?

**Comment by Prudential-Kenya** [comment]
The only fix now is to disable StickyGroupSeparators
`useStickyGroupSeparators: false`
or comment the line, it's false by default

Hope a fix will be pushed soon. I kinda like the StickyGroupSeparators. Thanks @Dimibe for this awesome package!👌

**Comment by Marcosmaliki** [comment]
The only fix now is to disable StickyGroupSeparators
useStickyGroupSeparators: false
or comment the line, it's false by default

Hope a fix will be pushed soon. I kinda like the StickyGroupSeparators. Thanks @Dimibe for this awesome package!👌

**Comment by Dimibe** [comment]
Sorry I am currently very busy and had no time to look into this issue. I hope I will find some time in the next two weeks or so. 
If anyone of you has already found a solution feel free to open a PR.

**Comment by luisdemarchi** [comment]
@Dimibe I know you’re out of time to fix it. But I just want to record that it also falls on the same bug :(

**Comment by CripyIce** [comment]
Also having this issue!
If anyone has any other solution except from `useStickyGroupSeparators: false` it will be great :)

**Comment by cata1992** [comment]
Just give  a new Key to your GroupedListView.

**Comment by BigJenson** [comment]
> Just give a new Key to your GroupedListView.

That actually works because it forces flutter to dump the old Widget and rebuild it. (set key: UniqueKey() in the Widget Contructor).

Can someone with flutter knowledge (just started with it) elaborate if that is a good idea or not?

**Comment by Dimibe** [comment]
Fixed with #110. Will be available in the next release.

**Comment by Sumit258000** [comment]
Facing same issue in another package [sticky_grouped_list: ^3.1.0](https://pub.dev/packages/sticky_grouped_list) @Dimibe can you please fix the same in this package also.
Thanks

**Comment by jonhcbs** [comment]
6.0.0  still have same issue  #221 ,  can this still work?      (set key: UniqueKey() in the Widget Contructor).
