### ISSUE TITLE
What's the difference between this package and sticky_grouped_list?

### ISSUE THREAD

**Issue by fenchai23** [Dimibe/grouped_list#79]
they both seem to do the same?

do they both support CustomScrollViews?

what is the difference?

**Comment by Dimibe** [comment]
The only difference is that the other package depends on the scrollable_positioned_list and this package depends on the standard list view. 
With the scrollable_positioned_list view it is possible to scroll directly to a specific item. 

The other (small) difference is, that in the other package always sticky headers are used, so the parameter "useStickyGroupSeparators" does not exists there.

**Comment by fenchai23** [comment]
> The only difference is that the other package depends on the scrollable_positioned_list and this package depends on the standard list view. 
> With the scrollable_positioned_list view it is possible to scroll directly to a specific item. 
> 
> The other (small) difference is, that in the other package always sticky headers are used, so the parameter "useStickyGroupSeparators" does not exists there. 

I see, very understandable, best solution would be merging both if it was possible but I can understand why.

Thanks for the clarification.

**Comment by Dimibe** [comment]
@fenchai23 
Yes, putting them in one package would be good. But I did not want to have any non dart/flutter core dependencies in this package. The benefit of that is e.g. that I could already publish a null-safe prerelease version. That would not be possible if packages I depend on did not support null-safety. 


In the future I will publish some more variants of grouped lists, e.g. one where you can collapse and expand the headers. This will than be part of this package and not an own package.
