### ISSUE TITLE
I have problem when grouping a list with SQLite

### ISSUE THREAD

**Issue by anonyran** [Dimibe/grouped_list#88]
Hello, I am newbie, and I have problem when grouping a list with SQLite, I get the error like in the picture
![Chưa có tên](https://user-images.githubusercontent.com/75026244/108609927-ffc8b680-7403-11eb-9d5b-d2feafeaebc2.png)

Please let me know where I was wrong, thank you and sorry for my english.

**Comment by KlubAndroid** [comment]
I have same problem with my db result, dont know how to convert to _element List type...
