### ISSUE TITLE
GroupBy more than 1 element

### ISSUE THREAD

**Issue by scrabbleknight** [Dimibe/grouped_list#91]
I'd like to be able to group my list by more than just one element. So that if there are several key/values in the list, we can group the list by more than just one element being the same. E.g. I have three elements, name, address and date, and I would like to be able to group these elements together if their address and their date are the same. I hope that makes sense - sorry I struggle to convey sometimes

**Comment by bobykurniawan11** [comment]
have you solve this ?

**Comment by Fintasys** [comment]
I've solved similar problem by using MapEntries for GroupBy
```
final _existingHeader = <MapEntry<String, int>>[];

GroupedListView<CustomObject, MapEntry<String, int>>(...

groupBy: (element) {
        var date = _timestampToDate(element.until!);
        /// check if matching group already exists
        var index = _existingHeader.indexWhere((e) => e.key == date);
        if (index == -1) {
            var entry =
                MapEntry(date, element.until!.millisecondsSinceEpoch);
            _existingHeader.add(entry);
            return entry;
        } else {
            return _existingHeader[index];
        }
},

...)
```

**Comment by Dimibe** [comment]
The option `groupComparator` can be used for this.
