### ISSUE TITLE
Remove background color?

### ISSUE THREAD

**Issue by luisdemarchi** [Dimibe/grouped_list#94]
Hi,

I left the list without a background color, I left the name of the groups without a background color. However, the group that is fixed at the top is always gray. How to remove?

<img width="652" alt="Screen Shot 2021-03-28 at 17 56 20" src="https://user-images.githubusercontent.com/461642/112767848-57ec6d00-8fef-11eb-969c-2bc2d4e8bad5.png">

**Comment by luisdemarchi** [comment]
I hid the background color by placing a white colored container. But what would be the ideal way?

```
Widget _buildGroupSeparator(dynamic groupByValue) {
    return Padding(
      padding: const EdgeInsets.only(top: 0, bottom: 0),
      child: Container(
          padding: EdgeInsets.only(top: kDefaultPadding + 10, bottom: 10),
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Text(
            groupByValue,
            textAlign: TextAlign.left,
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          )),
    );
  }
```

**Comment by Dimibe** [comment]
Hi @luisdemarchi, there a two options: 
Either you can set the property `stickyHeaderBackgroundColor` to the color you like or you can use the `floatingHeader` option to make the sticky header transparent.
