### ISSUE TITLE
On month change it create trouble

### ISSUE THREAD

**Issue by deep1931** [Dimibe/grouped_list#99]
Hello
Everything is working fine, as expected, but when months changed, it shows the elements on top which belong to date 1.

For example
we have chat items, and the last item is for 30 April 2021 but the message received on 1 May 2021 are listed on top it should be below 30 April not on top of the list. Tried to solve it but unable to fix it.

Screenshot attached 
![screen-group](https://user-images.githubusercontent.com/5684975/116784040-a2aa4a80-aaaf-11eb-8fb4-95849f8489b8.jpeg)

Please help.

**Comment by Fintasys** [comment]
I had a similar issue due to wrong result-value inside `groupComparator`. I was missing the equal case and the effect was that my group item weren't sorted.
```
groupComparator: (value1, value2) {
        if (value1.value > value2.value) {
                  return -1;
        } else if (value1.value < value2.value) {
                  return 1;
        } else {
                  return 0;
        }
},
``` 
If that's not the reason, it's better to post your code to see if something is wrong.

**Comment by Dimibe** [comment]
@deep1931 Is your problem solved? Could the answer from @Fintasys help you?

**Comment by deep1931** [comment]
@Fintasys Thanks I will try it.

@Dimibe I was busy with another project and could not test it, today i will test and revert you back...

**Comment by Dimibe** [comment]
Seems to be solved
